# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 241fc92b15e155d99367ed20ce6a6a7ff4f9c11b7feb16948d0944473df488c71d8119582116f5d91b469045b8ac2eaed4e0833075ee85744b1db0da3ac2b969

test:
  secret_key_base: 5968183688ef0b3b56d6fb70edcb99c180b33ad0d4ce88e150b115800ef4251892a8e930bd548e243c0f726a5f137e0f3781a1bf5b98e969c090a75ea84d1d3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
